apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: django-backend-vpa
  namespace: chatapp
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: django-backend
  updatePolicy:
    updateMode: "Auto"
