apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: chatapp
type: Opaque
data:
  DB_USER: YWRtaW4=        # Base64 encoded "admin"
  DB_PASSWORD: YWRtaW4xMjM=  # Base64 encoded "admin123"
